autosApp/config/routes.rb
Rails.application.routes.draw do
  get 'cars/index'

  root 'cars#index'
  resources :cars do
    resources :piezas
  end

end

autosApp/app/models/car.rb
class Car < ActiveRecord::Base

  has_many :piezas, dependent: :destroy

  validates :marca, presence: true
  validates :modelo, presence: true
  validates_numericality_of :lat, :greater_than_or_equal_to => -85.00, :less_than_or_equal_to => 85.00, :message => "debe estar en un rango entre -85 a 85"
  validates_numericality_of :long, :greater_than_or_equal_to => -180.00, :less_than_or_equal_to => 180.00, :message => "debe estar en un rango entre -180 a 180"

  after_initialize :init
  def init
    self.lat  ||= rand(-85.00...85.00)           #will set the default value only if it's nil
    self.long ||= rand(-180.00...180.00)         #ill set the default value only if it's nil
  end
end

autosApp/app/models/pieza.rb
class Pieza < ActiveRecord::Base
   belongs_to :car
   validates :nombre, presence: true
   validates :cantidad, presence: true
end

autosApp/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

autosApp/app/controllers/cars_controller.rb
class CarsController < ApplicationController

  def index
    @car = Car.all

  end

  def show
    @car = Car.find(params[:id])
    @hash = Gmaps4rails.build_markers(@car) do |car, marker|
      marker.lat car.lat
      marker.lng car.long
      marker.infowindow car.marca + "-" + car.modelo
    end
  end

  def new
    @car = Car.new
  end

  def edit
    @car = Car.find(params[:id])
  end

  def create
    @car = Car.new(cars_params)
    if @car.save
      redirect_to @car
    else
      render 'new'
    end
  end

  def update
    @car = Car.find(params[:id])

    if @car.update(cars_params)
      redirect_to @car
    else
      render 'edit'
    end
  end

  def destroy
    @car = Car.find(params[:id])
    @car.destroy
    redirect_to root_path
  end

  private
  def cars_params
    params.require(:car).permit(:marca, :modelo, :lat, :long)
  end
end

autosApp/app/controllers/piezas_controller.rb
class PiezasController < ApplicationController

  def show
    @car = Car.find(params[:car_id])
    @pieza = @car.piezas.find(params[:id])
  end

  def create
    @car = Car.find(params[:car_id])
    @pieza = @car.piezas.create(pieza_params)
    redirect_to car_path(@car)
  end

  def edit
    @car = Car.find(params[:car_id])
    @pieza = @car.piezas.find(params[:id])
  end

  def update
    @car = Car.find(params[:car_id])
    @pieza = @car.piezas.find(params[:id])
    if @pieza.update(pieza_params)
      redirect_to @car
    else
      render 'edit'
    end
  end
  def destroy
    @car = Car.find(params[:car_id])
    @pieza = @car.piezas.find(params[:id])
    @pieza.destroy
    redirect_to car_path(@car)
  end

  private
  def pieza_params
    params.require(:pieza).permit(:nombre, :cantidad)
  end

end

autosApp/app/helpers/application_helper.rb
module ApplicationHelper
end

autosApp/app/helpers/cars_helper.rb
module CarsHelper
end

autosApp/app/helpers/piezas_helper.rb
module PiezasHelper
end

autosApp/app/views/cars/edit.html.erb
<h1>Editar Carro</h1>

<%= form_for :car, :html => {:class => "formBorder"}, url: car_path(@car), method: :PATCH do |f|%>
    <% if @car.errors.any? %>
        <div id="error_explanation">
          <% @car.errors.full_messages.each do |msg| %>
              <div class="alert alert-danger alert-dismissible" role="alert">
                <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <strong>Error!</strong> <%= msg %>.
              </div>

          <% end %>

        </div>
    <% end %>
    <div class="form-group">
      <%= f.label :marca%></br>
      <%= f.text_field :marca, :class => 'form-control' %>
    </div>

    <div class="form-group">
      <%= f.label :modelo %></br>
      <%= f.text_field :modelo, :class => 'form-control' %>
    </div>

    <div class="form-group">
      <%= f.label :latitud %></br>
      <%= f.text_field :lat, :class => 'form-control' %>
    </div>

    <div class="form-group">
      <%= f.label :longitud %></br>
      <%= f.text_field :long, :class => 'form-control' %>
    </div>

    <p>
      <%= f.submit  'Guardar Cambios', :class => 'btn btn-success' %>
    </p>
<% end %>
</br>
<%= link_to 'Volver', cars_path %>

autosApp/app/views/cars/index.html.erb
<h1>Lista de Carros</h1>

<%= link_to 'Nuevo Carro', new_car_path %>

<table class="table table-bordered">
  <tr>
    <th>Marca</th>
    <th>Modelo</th>
    <th>Latitud</th>
    <th>Longitud</th>
    <th colspan="3">Opciones</th>
  </tr>

  <% @car.each do |car| %>
      <tr>
        <td><%= car.marca %></td>
        <td><%= car.modelo %></td>
        <td><%= car.lat %></td>
        <td><%= car.long %></td>
        <td><%= link_to 'Mostrar', car_path(car) %></td>
        <td><%= link_to 'Editar', edit_car_path(car) %></td>
        <td><%= link_to 'Eliminar', car_path(car),
                        method: :delete,
                        data: { confirm: 'Seguro que deseas eliminar el carro?' } %></td>
      </tr>
  <% end %>
</table>

autosApp/app/views/cars/new.html.erb
<h1>Crear Carro</h1>

<%= form_for :car, :html => {:class => "formBorder"}, url: cars_path do |f|%>
    <% if @car.errors.any? %>
        <div id="error_explanation">
          <% @car.errors.full_messages.each do |msg| %>
              <div class="alert alert-danger alert-dismissible" role="alert">
                <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <strong>Error!</strong> <%= msg %>.
              </div>

          <% end %>

        </div>
    <% end %>
    <div class="form-group">
      <%= f.label :marca%></br>
      <%= f.text_field :marca, :class => 'form-control' %>
    </div>

    <div class="form-group">
      <%= f.label :modelo %></br>
      <%= f.text_field :modelo, :class => 'form-control' %>
    </div>

    <p>
      <%= f.submit  'Guardar Carro', :class => 'btn btn-success' %>
    </p>
<% end %>
</br>
<%= link_to 'Volver', cars_path %>

autosApp/app/views/cars/show.html.erb
<div class="row borderInfoCar">
  <div class="col-xs-6" style="padding: 5%;">
    <p>
    <h2>Marca: <small> <%= @car.marca %></small></h2>
    </p>

    <p>
    <h2>Modelo: <small> <%= @car.modelo %></small></h2>
    </p>

    <p>
    <h2>Latitud: <small> <%= @car.lat %></small></h2>
    </p>

    <p>
    <h2>Longitud: <small> <%= @car.long %></small></h2>
    </p>
  </div>
  <div class="col-xs-6">
    <div id="map" style='width: 100%; height: 300px;'></div>
  </div>
</div>


<script>
  handler = Gmaps.build('Google');
  handler.buildMap({ provider: {}, internal: {id: 'map'}}, function(){
    markers = handler.addMarkers(<%=raw @hash.to_json %>);
    handler.bounds.extendWith(markers);
    handler.fitMapToBounds();
  });
</script>

<div class="borderInfoCar">
  <h2>Piezas</h2>
  <table class="table table-bordered">
    <tr>
      <th>Nombre</th>
      <th>Cantidad</th>
      <th colspan="2">Opciones</th>
    </tr>
    <%= render @car.piezas %>
  </table>
</div>
<div class="borderInfoCar">
  <h2>Agregar Pieza:</h2>
  <%= render 'piezas/form' %>
</div>
<%= link_to 'Editar Carro', edit_car_path(@car) %> |
<%= link_to 'Volver', cars_path %>

autosApp/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AutosApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <script src="//maps.google.com/maps/api/js?v=3.18&sensor=false&client=&key=&libraries=geometry&language=&hl=&region="></script>
  <script src="//google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js"></script>
  <!-- Latest compiled and minified CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
  <!-- Optional theme -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap-theme.min.css" integrity="sha384-fLW2N01lMqjakBkx3l/M9EahuwpSfeNvV63J5ezn3uZzapT0u7EYsXMjQV+0En5r" crossorigin="anonymous">
  <!-- Latest compiled and minified JavaScript -->
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="container">
  <div class="page-header">
    <h1>Página CRUD para el manejo de Carros <small> y piezas de carro</small></h1>
  </div>
  <%= yield %>
</div>
</body>
</html>

autosApp/app/views/piezas/_form.html.erb
<%= form_for([@car, @car.piezas.build]) do |f| %>
    <% if @car.errors.any? %>
        <div id="error_explanation">
          <% @car.errors.full_messages.each do |msg| %>
              <div class="alert alert-danger alert-dismissible" role="alert">
                <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <strong>Error!</strong> <%= msg %>.
              </div>

          <% end %>

        </div>
    <% end %>
    <div class="form-group">
      <%= f.label :nombre%></br>
      <%= f.text_field :nombre, :class => 'form-control' %>
    </div>
    <div class="form-group">
      <%= f.label :cantidad%></br>
      <%= f.text_field :cantidad, :class => 'form-control' %>
    </div>
    <p>
      <%= f.submit  'Guardar Pieza', :class => 'btn btn-success' %>
    </p>
<% end %>

autosApp/app/views/piezas/_pieza.html.erb
<tr>
  <td><%= pieza.nombre %></td>
  <td><%= pieza.cantidad %></td>
  <td><%= link_to 'Editar',edit_car_pieza_path(pieza.car, pieza)%></td>
  <td> <%= link_to 'Eliminar', [pieza.car, pieza],
                   method: :delete,
                   data: { confirm: 'Seguro que deseas eliminar la pieza?' } %></td>
</tr>

autosApp/app/views/piezas/edit.html.erb
<h1>Editar Pieza</h1>


<%= form_for :pieza, :html => {:class => "formBorder"}, url: car_pieza_path(@pieza.car,@pieza), method: :PATCH do |f|%>
    <% if @pieza.errors.any? %>
        <div id="error_explanation">
          <% @car.errors.full_messages.each do |msg| %>
              <div class="alert alert-danger alert-dismissible" role="alert">
                <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <strong>Error!</strong> <%= msg %>.
              </div>

          <% end %>

        </div>
    <% end %>
    <div class="form-group">
      <%= f.label :nombre%></br>
      <%= f.text_field :nombre, :class => 'form-control' %>
    </div>
    <div class="form-group">
      <%= f.label :cantidad%></br>
      <%= f.text_field :cantidad, :class => 'form-control' %>
    </div>
    <p>
      <%= f.submit  'Guardar Cambios', :class => 'btn btn-success' %>
    </p>
<% end %>
<%= link_to 'Volver', car_path(@car) %>

autosApp/app/views/piezas/show.html.erb
<div class="row borderInfoCar">
  <div class="col-xs-6" style="padding: 5%;">
    <p>
    <h2>Nombre: <small> <%= @pieza.nombre %></small></h2>
    </p>

    <p>
    <h2>Cantidad: <small> <%= @pieza.cantidad %></small></h2>
    </p>

  </div>
  <div class="col-xs-6" style="padding: 5%;">
    <%= link_to 'Editar Pieza', edit_car_path(@car) %> |
    <%= link_to 'Volver', cars_path %>
  </div>
</div>